FROM rockylinux:8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN yum install -y python36 python3-devel python3-ldap python3-pip openldap-devel gcc mariadb-devel xmlsec1 xmlsec1-openssl patch && \
    yum clean all && \
    rm -rf /var/cache/yum

WORKDIR /opt/userportal

COPY requirements.txt ./

RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.txt

COPY . .

RUN patch /usr/local/lib/python3.6/site-packages/ldapdb/backends/ldap/base.py < /opt/userportal/ldapdb.patch

EXPOSE 8000
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
