# Generated by Django 3.2.14 on 2022-08-24 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('ticket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('job_id', models.PositiveIntegerField(blank=True, null=True, validators=[notes.models.validate_job_id])),
                ('username', models.CharField(blank=True, max_length=255, null=True, validators=[notes.models.validate_valid_username])),
                ('account', models.CharField(blank=True, max_length=255, null=True, validators=[notes.models.validate_account])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-modified_at'],
            },
        ),
    ]
