# Generated by Django 5.0.7 on 2024-10-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobstats', '0001_initial'),
    ]

    operations = [
    ]
