# Generated by Django 3.2.16 on 2023-08-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobstats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('job_id', models.PositiveIntegerField(blank=True, null=True)),
                ('shared_with', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
